export const USER = {
    UPDATE_USER: "UPDATE_USER",
    SET_USERNAME: "SET_USERNAME",
    REMOVE_USERNAME: "REMOVE_USERNAME",
    GET_USER: "GET_USER",
    SET_ROLE: "SET_ROLE",
    REMOVE_CARINDETIALS: "REMOVE_CARINDETIALS",
    UPDATE_CAR_DETAILS: "UPDATE_CAR_DETAILS",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE"

};
export const CARMODAL = {
    CAR_DETAILS_FOR_EDIT: "CAR_DETAILS_FOR_EDIT",
    CAR_MODAL_VISIABLE: "CAR_MODAL_VISIABLE",
    CAR_MODAL_VISIABLE_ADD_TRUE: "CAR_MODAL_VISIABLE_ADD_TRUE",
    CAR_MODAL_VISIABLE_ADD_FALSE: "CAR_MODAL_VISIABLE_ADD_FALSE",
    CAR_MODAL_VISIABLE_EDIT_TRUE: "CAR_MODAL_VISIABLE_EDIT_TRUE",
    CAR_MODAL_VISIABLE_EDIT_FALSE: "CAR_MODAL_VISIABLE_EDIT_FALSE",

};
export const CAR_DETAILS = {
    UPDATE_CAR: "UPDATE_USER",
};